age=input("How old are you?")
height=input("How tall are you?")
weight=input("How much do you weigh?")
eye_color=input("eye color?")
print(f"So, you're {age} old, {height} tall, {weight} heavy and have {eye_color} eyes")
